// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/yodzafar/food-marketpalce/user-service/config"
	"github.com/yodzafar/food-marketpalce/user-service/internal/app"
	"github.com/yodzafar/food-marketpalce/user-service/internal/delivery/grpc"
	"github.com/yodzafar/food-marketpalce/user-service/internal/pkg/postgres"
	"github.com/yodzafar/food-marketpalce/user-service/internal/pkg/redis"
	"github.com/yodzafar/food-marketpalce/user-service/internal/repository"
	"github.com/yodzafar/food-marketpalce/user-service/internal/usecase"
)

// Injectors from wire.go:

func InitApp() (*app.App, error) {
	configConfig := config.LoadConfig()
	db, err := postgres.New(configConfig)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(db)
	client, err := redis.New(configConfig)
	if err != nil {
		return nil, err
	}
	userCache := repository.NewUserCache(client)
	userService := usecase.NewUserUseCase(userRepository, userCache)
	userHandler := grpcdelivery.NewUserHandler(userService)
	appApp := app.New(configConfig, userHandler)
	return appApp, nil
}
