// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/yodzafar/food-market/api-gateway/config"
	"github.com/yodzafar/food-market/api-gateway/internal/app"
)

// Injectors from wire.go:

func initApp() (*app.App, error) {
	configConfig := config.Load()
	appApp, err := app.New(configConfig)
	if err != nil {
		return nil, err
	}
	return appApp, nil
}
